### ISSUE TITLE
page is not loading 

### ISSUE THREAD

**Issue by shaytoMoonActive** [hbatalhaStch/react-big-scheduler#13]
### Checklist

- [X] I've verified that I'm running react-big-scheduler-stch version **1.2.2**

### Describe the bug

blank page when opening https://stephenchou1017.github.io/scheduler/#/

here is the error in the console :
to load resource: the server responded with a status of 403 ()
react.production.min.js:1 Failed to load resource: the server responded with a status of 403 ()
moment.min.js:1 Failed to load resource: the server responded with a status of 403 ()
zh-cn.js:1 Failed to load resource: the server responded with a status of 403 ()
polyfill.min.js:1 Failed to load resource: the server responded with a status of 403 ()
bundle.js:1 Uncaught ReferenceError: React is not defined
at Object. (bundle.js:1:975)
at n (bundle.js:1:110)
at Object. (bundle.js:32:839950)
at n (bundle.js:1:110)
at Object. (bundle.js:32:839905)
at n (bundle.js:1:110)
at bundle.js:1:902
at bundle.js:1:913

### Reproduction Link/Code

here is the error in the console :
to load resource: the server responded with a status of 403 ()
react.production.min.js:1 Failed to load resource: the server responded with a status of 403 ()
moment.min.js:1 Failed to load resource: the server responded with a status of 403 ()
zh-cn.js:1 Failed to load resource: the server responded with a status of 403 ()
polyfill.min.js:1 Failed to load resource: the server responded with a status of 403 ()
bundle.js:1 Uncaught ReferenceError: React is not defined
at Object. (bundle.js:1:975)
at n (bundle.js:1:110)
at Object. (bundle.js:32:839950)
at n (bundle.js:1:110)
at Object. (bundle.js:32:839905)
at n (bundle.js:1:110)
at bundle.js:1:902
at bundle.js:1:913

### Steps to reproduce

go to : https://stephenchou1017.github.io/scheduler/#/

**Comment by hbatalhaStch** [comment]
The error you are getting is not related to this library, it looks like there's some problem with your browser/internet connection.
